# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OpenServer\domains\confidential\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 369)
        Form.setMouseTracking(True)
        Form.setTabletTracking(True)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(80, 80, 281, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setMouseTracking(True)
        self.calendarWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calendarWidget.setStyleSheet(
            "/****************************************/\n"
            "QCalendarWidget QWidget {\n"
            "    alternate-background-color: rgba(0, 0, 0, 40);\n"
            "    outline:0;\n"
            "}\n"
            "\n"
            "QCalendarWidget QTableView QHeaderView::section {\n"
            "    /*font-family:Myriad;*/\n"
            "}\n"
            "\n"
            "#qt_calendar_navigationbar {\n"
            "    /*background-color: rgba(250, 0, 0, 150);*/\n"
            "    background-color: rgb(240, 240, 240);\n"
            "    border: 1px solid rgb(173, 173, 173);\n"
            "}\n"
            "\n"
            "/****************************************/\n"
            "\n"
            "#qt_calendar_monthbutton,#qt_calendar_yearbutton {\n"
            "    margin-top: 5px;\n"
            "    margin-bottom: 5px;\n"
            "    font-size:15px;\n"
            "    color: rgb(0, 0, 0);\n"
            "    border:1;\n"
            "}\n"
            "#qt_calendar_monthbutton{\n"
            "    padding-left:0;\n"
            "    padding-right:auto;\n"
            "    margin-left:0;\n"
            "    margin-right:0;\n"
            "}\n"
            "#qt_calendar_yearbutton {\n"
            "    padding-left:auto;\n"
            "    padding-right:0;\n"
            "    margin-left:auto;\n"
            "    margin-right:0;\n"
            "}\n"
            "#qt_calendar_monthbutton:hover,#qt_calendar_yearbutton:hover {\n"
            "    color: rgba(0, 0, 0,100);\n"
            "}\n"
            "\n"
            "#qt_calendar_yearedit {\n"
            "    margin-left:0px;\n"
            "    min-width: 10px;\n"
            "    color: #000;\n"
            "    background: transparent;\n"
            "    font-size: 15px;\n"
            "}\n"
            "#qt_calendar_yearedit::up-button { \n"
            "    image: url(Assets/up.svg);\n"
            "}\n"
            "\n"
            "#qt_calendar_yearedit::down-button { \n"
            "    image: url(Assets/down.svg);\n"
            "}\n"
            "\n"
            "#qt_calendar_yearedit::down-button, \n"
            "#qt_calendar_yearedit::up-button {\n"
            "    width:20;\n"
            "    border-radius:5px;\n"
            "\n"
            "}\n"
            "#qt_calendar_yearedit::down-button:hover, \n"
            "#qt_calendar_yearedit::up-button:hover {\n"
            "    background-color: rgba(0, 0, 0,40);\n"
            "}\n"
            "#qt_calendar_monthbutton::menu-indicator {\n"
            "     image: none;\n"
            "}\n"
            "\n"
            "/****************************************/\n"
            "\n"
            "#qt_calendar_prevmonth {\n"
            "    padding-left:15px;\n"
            "    image: url(Assets/back.svg);\n"
            "}\n"
            "#qt_calendar_nextmonth {\n"
            "    padding-right:10;\n"
            "    image: url(Assets/next.svg);\n"
            "}\n"
            "\n"
            "#qt_calendar_prevmonth,#qt_calendar_nextmonth {\n"
            "    border:1px;\n"
            "    qproperty-icon:none;\n"
            "}\n"
            "#qt_calendar_prevmonth:hover, \n"
            "#qt_calendar_nextmonth:hover {\n"
            "    background-color: rgba(0, 0, 0,40);\n"
            "}\n"
            "\n"
            "/****************************************/\n"
            "#qt_calendar_calendarview {\n"
            "    /* Remove the selected dashed box */\n"
            "    outline: 0px;\n"
            "\n"
            "    border: 1px solid rgb(173, 173, 173);\n"
            "    border-top: 0px;\n"
            "}\n"
            "\n"
            ""
        )
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setVerticalHeaderFormat(
            QtWidgets.QCalendarWidget.ISOWeekNumbers
        )
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditAcceptDelay(0)
        self.calendarWidget.setObjectName("calendarWidget")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(220, 80, 31, 31))
        self.pushButton.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    background:transparent;\n"
            "\n"
            "}\n"
            "QPushButton:hover {\n"
            "    \n"
            "    background-color: rgba(0, 0, 0, 40);\n"
            "}"
        )
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/newPrefix/Assets/today.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


import res_rc
